#!/usr/bin/env node
// Auto-generated by cicd-kit. Safe to edit.
// Source of truth: src/utils/detect.js

const fs   = require('fs');
const path = require('path');

function fileExists(f) { return fs.existsSync(path.join(process.cwd(), f)); }
function setOutput(name, value) {
  const out = process.env.GITHUB_OUTPUT;
  if (out) fs.appendFileSync(out, `${name}=${value}\n`);
  else console.log(`  → ${name}=${value}`);
}
function readJson(f) {
  try { return JSON.parse(fs.readFileSync(path.join(process.cwd(), f), 'utf8')); }
  catch { return null; }
}

const FRAMEWORKS = [
  ['next','nextjs','.next'],
  ['nuxt','nuxt','.output'],
  ['@nuxt/core','nuxt','.output'],
  ['@sveltejs/kit','sveltekit','build'],
  ['astro','astro','dist'],
  ['@remix-run/react','remix','build'],
  ['@remix-run/node','remix','build'],
  ['gatsby','gatsby','public'],
  ['react-scripts','cra','build'],
  ['@angular/core','angular','dist'],
  ['@vue/cli-service','vue-cli','dist'],
  ['vue','vue','dist'],
  ['vite','vite','dist'],
  ['express','express','.'],
  ['fastify','fastify','.'],
  ['hono','hono','dist'],
  ['@nestjs/core','nestjs','dist']
];
const NODE_VERSION_MAP = {   'nextjs':'20',   'nuxt':'20',   'sveltekit':'20',   'astro':'20',   'remix':'20',   'gatsby':'18',   'cra':'18',   'angular':'20',   'vue':'18',   'vue-cli':'18',   'vite':'20',   'express':'20',   'fastify':'20',   'hono':'20',   'nestjs':'20' };
const NO_BUILD = ['express', 'fastify', 'hono'];
const PM_RUN   = { npm:'npm run', pnpm:'pnpm run', yarn:'yarn', bun:'bun run' };

const pkg = readJson('package.json');
if (!pkg) { console.error('❌  No package.json found.'); process.exit(1); }

const deps    = { ...pkg.dependencies, ...pkg.devDependencies };
const scripts = pkg.scripts || {};

console.log('\n🔍 Detecting project configuration...\n');

// Package manager
let pm = 'npm';
if (pkg.packageManager) {
  const p = pkg.packageManager.split('@')[0].toLowerCase();
  if (['npm','pnpm','yarn','bun'].includes(p)) pm = p;
}
if      (fileExists('bun.lockb') || fileExists('bun.lock')) pm = 'bun';
else if (fileExists('pnpm-lock.yaml'))                       pm = 'pnpm';
else if (fileExists('yarn.lock'))                            pm = 'yarn';
else if (fileExists('package-lock.json'))                    pm = 'npm';
console.log(`📦  Package manager : ${pm}`);

// Framework
let framework = 'unknown', outputDir = 'dist';
for (const [dep, key, out] of FRAMEWORKS) {
  if (deps[dep]) { framework = key; outputDir = out; break; }
}
console.log(`🧩  Framework       : ${framework}`);

// Node version
let nodeVersion = '20';
if (pkg.engines?.node) { const m = pkg.engines.node.match(/(\d+)/); if (m) nodeVersion = m[1]; }
else nodeVersion = NODE_VERSION_MAP[framework] || '20';
console.log(`🔧  Node version    : ${nodeVersion}`);

// Build command
const run = PM_RUN[pm];
const buildCommand = scripts.build
  ? `${run} build`
  : NO_BUILD.includes(framework)
    ? `echo "No build step required for ${framework}"`
    : `${run} build`;
console.log(`🏗️   Build command   : ${buildCommand}`);
console.log(`📂  Output dir      : ${outputDir}`);

// Deploy target
const deployTarget = (process.env.DEPLOY_TARGET || 'custom').toLowerCase();
console.log(`🚀  Deploy target   : ${deployTarget}`);

setOutput('package_manager', pm);
setOutput('framework',       framework);
setOutput('node_version',    nodeVersion);
setOutput('build_command',   buildCommand);
setOutput('output_dir',      outputDir);
setOutput('deploy_target',   deployTarget);

console.log('\n✅  Detection complete.\n');
